controller_manager:
  ros__parameters:
    update_rate: 10  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint1_position_controller:
      type: passthrough_controller/PassthroughController

    joint2_position_controller:
      type: passthrough_controller/PassthroughController

    test_position_controller:
      type: passthrough_controller/PassthroughController

    forward_position_controller:
      type: forward_command_controller/ForwardCommandController

# First-level controllers
joint1_position_controller:
  ros__parameters:
    interfaces: ["joint1/position"]
    joints: ["jw"]
    gensys: ["gn"]

joint2_position_controller:
  ros__parameters:
    interfaces: ["joint2/position"]
    joints: ["jww"]
    gensys: ["gn2"]


test_position_controller:
  ros__parameters:
    joints: ["j1", "j2"]
    gensys: ["djs"]

# Third-level controllers
forward_position_controller:
  ros__parameters:
    joints:
      - test_position_controller/joint1_position_controller/joint1
      - test_position_controller/joint2_position_controller/joint2
    interface_name: position
