
# Second-level controller
test_position_controller:
  ros__parameters:
    interfaces:
      - joint1_position_controller/joint1/position
      - joint2_position_controller/joint2/position
    joints: ["j1", "j2"]
    gensys: ["djs"]
    gains:
      j1:
        p: 20.0
      j2:
        p: 10.0